services:
  - type: web
    name: rentx-api
    env: node
    region: ohio
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: rentx-db
          property: connectionString

databases:
  - name: rentx-db
    plan: free
    databaseName: rentx_db
    user: rentx_user
